spring:
  main:
    web-application-type: none
  security:
    oauth2:
      client:
        registration:
          application:
            authorization-grant-type: client_credentials
            client-id: # your application client id
            client-secret: # your application client secret
        provider:
          application:
            token-uri: # your application token endpoint
  datasource:
    hikari:
      username: #your database username
      password: #your database password
      auto-commit: off
      connection-test-query: #your connection test query
      validation-timeout: #your validation timeout
      minimum-idle: #your minimum idle
      maximum-pool-size: #your maximum pool size
      connection-timeout: #your connection timeout
    driver-class-name: #your driver class name
    url: #your database url
    sql-script-encoding: UTF-8
    platform: mariadb
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
mybatis:
  mapper-locations: mapper/**/*.xml
  type-handlers-package: cube8540.book.batch.config
api:
  connection:
    max-awit-second: 5
    retry-count: 1
    retry-delay-second: 5
  endpoint:
    application:
      upstream: # your application upstream endpoint
      host: #your application host
  authentication:
    national-library:
      key: # your national library api key
    naver-book:
      client-id: # your naver book api client id
      client-secret: # your naver api client secret
    kyobo:
      username: # your https://www.kyobobook.co.kr login username
      password: # your https://www.kyobobook.co.kr login password
    aladin:
      ttb-key: # your aladin ttb key